### ISSUE TITLE
install.sh should use asahi-fwextract-compat

### ISSUE THREAD

**Issue by wazdra** [chadmed/asahi-gentoosupport#10]
Something goes wrong with asahi-fwextract, because asahi_firmware.update expects a path to a manifest. Even when providing such a path, things are still not working, but the compat version works fine…
I’ll try to send the failure in this last case if need be but first I’ve got to finish my gentoo install to get to GitHub ^^

**Comment by chadmed** [comment]
Ah I see what's happened, the -r2 ebuild of the stable version installs the wrong `asahi-fwextract` script. I'll fix this soon.
