### ISSUE TITLE
GRUB: `error: extent not found.`

### ISSUE THREAD

**Issue by monomycelium** [chadmed/asahi-gentoosupport#14]
I used `btrfs` for my root filesystem. However, when booting GRUB, I get this:

![PXL_20230216_090037378.MP~2.jpg](https://user-images.githubusercontent.com/95113443/219317891-b0866db1-1005-44b5-80f8-555a9d00f6e0.jpg)

I've tried `btrfs` on Gentoo for Asahi before, but I haven't seen this before. I cannot give you any more information because I am switching to `ext4` right now.

**Comment by jaredallard** [comment]
I've installed it with btrfs a few times and didn't hit this. We can probably mark this as non-reproducible.

**Comment by chadmed** [comment]
I agree. I hit it once ages ago but haven't since. I now use ESP-as-boot anyway and recommend others do the
same on Apple Silicon since it enables you to more easily recovery your kernel/initramfs if something goes wrong.
