### ISSUE TITLE
Current Gentoo LiveCD needs a little more space on ramdisk

### ISSUE THREAD

**Issue by ivabus** [chadmed/asahi-gentoosupport#6]
I got some errors (no more space left on device) with current genstrap.sh. To fix I just added more space in modprobe line

**Comment by chadmed** [comment]
How much extra space did you require?

**Comment by jannau** [comment]
we could save space by compressing the modules with gzip, bzip2, xz depending on that the gentoo livecd kmod supports

**Comment by chadmed** [comment]
The base Gentoo profile has `lzma` in USE. That flag governs whether or not `kmod` is built with xz support,
so we should be safe to compress the modules with xz. I'll get on to that some time later this week if no one has
beaten me to it.

**Comment by ivabus** [comment]
I just multiplied the current size by 1.5 and it was enough for me

**Comment by monomycelium** [comment]
How do I increase the size? I'm not too familiar with `parted`, but I can use `fdisk` pretty well.

---

### edit

nevermind, i just increased it in the `modprobe` line and rebooted and ran the script again.

**Comment by Leo3418** [comment]
As of recently, I need to increase the RAM disk capacity to 1048576 KiB to successfully build an image.  Can someone else confirm?  Is any update to the script needed?

**Comment by ekhodx** [comment]
> As of recently, I need to increase the RAM disk capacity to 1048576 KiB to successfully build an image. Can someone else confirm?

Same for me. I got "no space left on device". Increasing capacity helps.

**Comment by kdb424** [comment]
I likewise had to increase the ramdisk in size. I changed it to double without thinking and had zero issues after. I didn't bother chasing the minimum size as it would likely change over time.
