### ISSUE TITLE
`asahi-fwextract: /usr/sbin/update-vendor-firmware not found`

### ISSUE THREAD

**Issue by monomycelium** [chadmed/asahi-gentoosupport#8]
```
==> Upgrading vendor firmware package...
    Firmware upgraded
/usr/sbin/asahi-fwextract: line 17: /usr/sbin/update-vendor-firmware: No such file or directory
```

Should I have installed the script? Can I reboot now?

**Comment by chadmed** [comment]
ah thats a problem with the ebuild in the overlay. please emerge sys-apps/asahi-scripts and then run asahi-fwextract. you should be able to reboot safely after that

EDIT: it's a problem with the keywording actually. the way we handle firmware now has not been keyworded for `arm64`, only `~arm64`. i'll fix this later today.

**Comment by monomycelium** [comment]
When I run `asahi-fwextract` after emerging `sys-apps/asahi-scripts`, the same error occurs.

---

### Resolution

Apparently, the path was wrongly set in the `asahi-fwextract`. The scripts were installed to `/usr/local`, as in `/usr/local/bin/update-vendor-firmware`.

To solve the problem, I just symlinked `/usr/local/bin/*` to `/usr/sbin/` (because there was nothing else) and `/usr/local/share/asahi-scripts` to `/usr/share/`.

**Comment by chadmed** [comment]
I see exactly what has happened, fix coming soon
